In [1]:
# import pandas
import pandas as pd

In [2]:
# load the data
df = pd.read_csv("cafe_sales_practice.csv")

In [55]:
df

,Orderid,Orderdate,Customername,Item,Category,Quantity,Unitprice,Totalprice,Paymentmethod,City,Rating
0,1041,2025-03-12,Rahul Reddy,Burger,Food,2.0,180.0,360.0,Cash,Bengaluru,2.0
1,1052,2025-01-15,Priya Bhat,Cheesecake,dessert,3.0,170.0,510.0,UPI,Chennai,3.0
2,1140,2025-04-04,Unknown,Chocolate Cake,dessert,1.0,180.0,180.0,Cash,Mumbai,5.0
3,1198,2025-03-31,Unknown,Cheesecake,Dessert,1.0,170.0,170.0,UPI,Pune,5.0
4,1171,2025-06-14,Anjali Reddy,Ice Cream,Dessert,2.0,130.0,260.0,Card,Pune,5.0
...,...,...,...,...,...,...,...,...,...,...,...
195,1001,2025-01-25,Ishaan Mehta,Iced Tea,Beverage,1.0,120.0,120.0,Cash,Kolkata,5.0
196,1185,2025-01-06,Manish Gupta,Ice Cream,dessert,1.0,130.0,130.0,UPI,Mumbai,3.0
197,1132,2025-04-25,Manish Sharma,Ice Cream,Dessert,1.0,130.0,130.0,UPI,Pune,2.0
198,1153,2025-06-07,Rahul Malhotra,Bagel,BAKERY,2.0,100.0,200.0,Card,Chennai,1.0
199,1107,2025-02-20,Unknown,Bagel,BAKERY,1.0,100.0,100.0,Wallet,Hyderabad,4.0

In [56]:
df.columns = df.columns.str.lower().str.title()

In [60]:
df['Category'] = df['Category'].str.title()

In [62]:
df['Category'].unique()

<StringArray>
['Food', 'Dessert', 'Beverage', 'Bakery', 'Beverages']
Length: 5, dtype: str

In [63]:
category = {
    'Beverage':'Beverages'
}

In [64]:
df['Category'] = df['Category'].replace(category)

In [65]:
df['Category'].unique()

<StringArray>
['Food', 'Dessert', 'Beverages', 'Bakery']
Length: 4, dtype: str

In [4]:
# count the nulls
df.isnull().sum()

OrderID           0
OrderDate         0
CustomerName     15
Item              0
Category          0
Quantity          3
UnitPrice         7
TotalPrice       17
PaymentMethod     8
City              0
Rating            5
dtype: int64

In [10]:
df['CustomerName']

0         Rahul Reddy
1          Priya Bhat
2                 NaN
3                 NaN
4        Anjali Reddy
            ...
195      Ishaan Mehta
196      Manish Gupta
197     Manish Sharma
198    Rahul Malhotra
199               NaN
Name: CustomerName, Length: 200, dtype: str

In [11]:
df['CustomerName'] = df['CustomerName'].fillna('Unknown')

In [13]:
df['CustomerName']

0         Rahul Reddy
1          Priya Bhat
2             Unknown
3             Unknown
4        Anjali Reddy
            ...
195      Ishaan Mehta
196      Manish Gupta
197     Manish Sharma
198    Rahul Malhotra
199           Unknown
Name: CustomerName, Length: 200, dtype: str

In [28]:
unit_price = df['UnitPrice'].mean().round(0)

In [29]:
unit_price

np.float64(143.0)

In [19]:
df['UnitPrice'] = df['UnitPrice'].fillna(unit_price)

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        200 non-null    int64
 1   OrderDate      200 non-null    datetime64[us]
 2   CustomerName   200 non-null    str
 3   Item           200 non-null    str
 4   Category       200 non-null    str
 5   Quantity       197 non-null    float64
 6   UnitPrice      200 non-null    float64
 7   TotalPrice     183 non-null    float64
 8   PaymentMethod  192 non-null    str
 9   City           200 non-null    str
 10  Rating         195 non-null    float64
dtypes: datetime64[us](1), float64(4), int64(1), str(5)
memory usage: 17.3 KB

In [22]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

In [20]:
df.isnull().sum()

OrderID           0
OrderDate         0
CustomerName      0
Item              0
Category          0
Quantity          3
UnitPrice         0
TotalPrice       17
PaymentMethod     8
City              0
Rating            5
dtype: int64

In [32]:
quantity = df['Quantity'].median()

In [33]:
# fill quantity 
df['Quantity'] = df['Quantity'].fillna(quantity)

In [38]:
total = df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

In [39]:
df['TotalPrice'] = df['TotalPrice'].fillna(total)

In [42]:
df['PaymentMethod'] = df['PaymentMethod'].fillna('Unknown')

In [43]:
df['PaymentMethod'].isnull().sum()

np.int64(0)

In [48]:
rating = df['Rating'].median()

In [49]:
df['Rating'] = df['Rating'].fillna(rating)

In [51]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerName     0
Item             0
Category         0
Quantity         0
UnitPrice        0
TotalPrice       0
PaymentMethod    0
City             0
Rating           0
dtype: int64

In [67]:
df

,Orderid,Orderdate,Customername,Item,Category,Quantity,Unitprice,Totalprice,Paymentmethod,City,Rating
0,1041,2025-03-12,Rahul Reddy,Burger,Food,2.0,180.0,360.0,Cash,Bengaluru,2.0
1,1052,2025-01-15,Priya Bhat,Cheesecake,Dessert,3.0,170.0,510.0,UPI,Chennai,3.0
2,1140,2025-04-04,Unknown,Chocolate Cake,Dessert,1.0,180.0,180.0,Cash,Mumbai,5.0
3,1198,2025-03-31,Unknown,Cheesecake,Dessert,1.0,170.0,170.0,UPI,Pune,5.0
4,1171,2025-06-14,Anjali Reddy,Ice Cream,Dessert,2.0,130.0,260.0,Card,Pune,5.0
...,...,...,...,...,...,...,...,...,...,...,...
195,1001,2025-01-25,Ishaan Mehta,Iced Tea,Beverages,1.0,120.0,120.0,Cash,Kolkata,5.0
196,1185,2025-01-06,Manish Gupta,Ice Cream,Dessert,1.0,130.0,130.0,UPI,Mumbai,3.0
197,1132,2025-04-25,Manish Sharma,Ice Cream,Dessert,1.0,130.0,130.0,UPI,Pune,2.0
198,1153,2025-06-07,Rahul Malhotra,Bagel,Bakery,2.0,100.0,200.0,Card,Chennai,1.0
199,1107,2025-02-20,Unknown,Bagel,Bakery,1.0,100.0,100.0,Wallet,Hyderabad,4.0

In [19]:
df['Item'].value_counts()

Item
Bagel             18
Cheesecake        14
Chocolate Cake    13
Latte             12
Espresso          12
Burger            11
Hot Chocolate     11
Croissant         11
Muffin            11
Salad             11
Cappuccino        10
Iced Tea          10
Sandwich          10
Cold Brew         10
Brownie            8
Ice Cream          7
Pasta              6
Name: count, dtype: int64

In [20]:
# remove duplicate rows from your dataset.
df = df.drop_duplicates()

In [21]:
df.duplicated().sum()

np.int64(0)

In [24]:
# groupby() to find total revenue for Category, City, and Month.
# Revenue by Category
revenue_by_category = df.groupby('Category')['TotalPrice'].sum().sort_values(ascending=False)
print(revenue_by_category)

Category
Food         11470.0
Beverage     10350.0
Dessert       9270.0
Bakery        8880.0
Beverages     6130.0
Name: TotalPrice, dtype: float64

In [25]:
# Revenue by City
revenue_by_city = df.groupby('City')['TotalPrice'].sum().sort_values(ascending=False)
print(revenue_by_city)

City
Pune         8200.0
Mumbai       7530.0
Delhi        7410.0
Chennai      6760.0
Bengaluru    5780.0
Hyderabad    5260.0
Kolkata      5160.0
Name: TotalPrice, dtype: float64

In [26]:
# Revenue by Month
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

revenue_by_month = df.groupby(df['OrderDate'].dt.month)['TotalPrice'].sum()
print(revenue_by_month)

OrderDate
1    11060.0
2     9020.0
3     5600.0
4     5070.0
5     6180.0
6     5690.0
7     3480.0
Name: TotalPrice, dtype: float64